### ISSUE TITLE
Cannot able to compile the kernel seems to have some error 

### ISSUE THREAD

**Issue by nervehammer** [pinnamanivenkat/kernel_coolpad_CP8676_I02#1]
root@HAMM3RN:/mnt/g/kernel# ./kernel.sh
arch/arm64/configs/CP8676_I02_defconfig:1403:warning: override: reassigning to symbol MTK_LENS_DW9718AF_SUPPORT
arch/arm64/configs/CP8676_I02_defconfig:1433:warning: override: reassigning to symbol MTK_FLASHLIGHT
#
# configuration written to .config
#
scripts/kconfig/conf --silentoldconfig Kconfig
/mnt/g/kernel/tools/dct/DrvGen: 1: /mnt/g/kernel/tools/dct/DrvGen: Syntax error: word unexpected (expecting ")")
make: *** [/mnt/g/kernel/drivers/misc/mediatek/mach/mt6735/CP8676_I02/dct/dct/cust_adc.dtsi] Error 2
root@HAMM3RN:/mnt/g/kernel#

**Comment by pinnamanivenkat** [comment]
You have been doing something wrong.
Check if all dependencies are installed correct.
Have tested just now.
